### ISSUE TITLE
Firmware 1.4.10 issue

### ISSUE THREAD

**Issue by davidefava** [charleslemaire0/TeenAstro#65]
Please check the effective motor speed. With the new update they move a 1/100 or less than the normal.
During goto you could hear the sound of the motors but barely see the movement. 
I tested two different teenastro on two different mount and i uploaded data with two different .tac files.
I tried another spare teenastro with 1.2.x on the same mount and worked, also reinstalling a 1.3.x firmware where it was 1.4.10 worked well.

**Comment by MasterPIC** [comment]
Current implementation adds 3 decimals digits to gear value (previously it was an integer) and the dot char you see is a decimal separator. So you have to update the gear reduction ratio.

**Comment by messschuh** [comment]
today i update the SHC and MainUnit to the newest firmware, change the old gear setting 4320 to 4320,000. the problem is, the old goto speed was x960 and now the i can go max to x480. steps/r and microsteps are the same like before. the true speed looks like like the same but im confused about the speed setting ( old x960, new x480). is it a bug or have i an understanding problem?

**Comment by charleslemaire0** [comment]
And if you power cycle the main unit is it the same?

**Comment by messschuh** [comment]
tried again today and it is the same, when i go higher than x480 the mount stops and the motors make a lot of noise. unfortunately i cant check if the tracking speed works correct because of cloudy sky.  i will try to go back to older firmware version to confirm the issue.

**Comment by messschuh** [comment]
i compiled and flash 1.4.6 for MU and 1.4.3 for the SHC and had the same issue, then i realized i forgot that the current Motors at the Mount have 3.6° step angle and not 1.8° . so stupid. my misstake, sorry for the confusion.
